### ISSUE TITLE
could not be installed

### ISSUE THREAD

**Issue by kimuxer** [arcolinux/arcolinux-hyprland#1]
I downloaded the hyprland.iso V23.01.03, burned it to the U disk and restarted it. I stayed in the login interface and could not enter the system. After clicking login, the screen went black for a few seconds and then returned to the login interface
By the way，sway same situation

Sorry my English is not good

**Comment by arcolinuxz** [comment]
Listen to the videos

and

know when it will NEVER EVER launch

happy holidays

erik
