### ISSUE TITLE
Interval time of Waybar custom/updater too short 

### ISSUE THREAD

**Issue by SomeCoder001** [arcolinux/arcolinux-hyprland#3]
Is it intentional that the interval time of the custom/updater module of Waybar is set to 15 seconds?
Seems pretty short for updating packages. My DNS Server got a few thousand DNS requests because of this, and even rate limited my client. I would remove the interval completely and only wait for user input.

**Comment by arcolinuxz** [comment]
thanks for bringing this to my attention
I will instantly look into it

**Comment by arcolinuxz** [comment]
changed to 3 hours
